development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://rediscloud:BiwpLqWkbE8TSPgk@redis-17704.c6.eu-west-1-1.ec2.cloud.redislabs.com:17704
  channel_prefix: ninjaquizz_production
