meta_product_name: "NinjaQuiz"
meta_title: "NinjaQuiz - Show who's the boss. Become a ninja!"
meta_description: "Ninja is an app allowing a host to create and animate a trivia game that several guests can join and participate to on their phone"
meta_image: "cover.jpg"                       # should exist in `app/assets/images/`
