meta_product_name: "Ninjaquiz"
meta_title: "Ninjaquiz - Become your own trivia game host"
meta_description: "Ninja is an app allowing a host to create and animate a trivia game that several guests can join and participate to on their phone"
meta_image: "cover.jpeg"                       # should exist in `app/assets/images/`
